### PR TITLE
Logo Idea

### PR DESCRIPTION
**Pull request by lbonillaii**
Hactoberfest logo idea for Flippy Floppy #2 

flippyfloppylogo

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Can we use a sans serif font? Also, please re-do the Fs as they're a bit out of proportion and not aligned at the top.

Some inspiration may help 😄

**Comment by lbonillaii** [comment]
Here are some adjustments #2 

flippyfloppylogo

**Comment by shakeelmohamed** [comment]
Looks better! Can we see a square version? It needs to fit as a profile photo: https://github.com/flippy-flop

**Comment by lbonillaii** [comment]
How's this? The background is white so it's hard to see the square layout, recommend downloading the image to see correctly

flippyfloppylogo

**Comment by shakeelmohamed** [comment]
I'll take it! Thanks @lmboricua

**Comment by lbonillaii** [comment]
@shakeelmohamed no problem!

**Pull request merged**
